version: '3.7'

services:
  node:
    container_name: snakechain_node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./snakechain/node:/app
      - ./docker/node/entrypoint.sh:/entrypoint.sh
    command: /./entrypoint.sh
    environment:
      - CACHE_HOST=redis-cache
      - STORAGE_HOST=redis-storage
      - REDIS_PORT=6379
    depends_on:
      - redis-cache
      - redis-storage

  redis-cache:
    container_name: snakechain_redis_cache
    image: redis
