version: '3.7'

services:
  node:
    container_name: snakechain_node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./snakechain:/app
      - ./docker/node/entrypoint.sh:/entrypoint.sh
      - ./docker/node/compile_proto.sh:/compile_proto.sh
      - ./docker/node/formatter.sh:/formatter.sh
      - ./docker/node/wait_for_storage.sh:/wait_for_storage.sh
    command: /./entrypoint.sh
    environment:
      - BUFFER_HOST=buffer
      - BUFFER_PORT=6379
      - STORAGE_HOST=storage
      - STORAGE_USER=storage
      - STORAGE_PASSWORD=password
    depends_on:
      - buffer
      - storage

  buffer:
    container_name: snakechain_buffer
    image: redis

  storage:
    container_name: snakechain_storage
    image: couchbase:community
    volumes:
    - ./docker/storage/configure.sh:/configure.sh
    command: /./configure.sh
    environment:
      - STORAGE_USER=storage
      - STORAGE_PASSWORD=password
    ports:
      - 8091:8091
