version: '3.7'

services:
  node:
    container_name: snakechain_node
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./snakechain:/app
      - ./docker/entrypoint.sh:/entrypoint.sh
    command: /./entrypoint.sh
    environment:
      - BUFFER_HOST=buffer
      - BUFFER_PORT=6379
    depends_on:
      - storage
      - buffer

  storage:
    container_name: snakechain_storage
    image: couchbase

  buffer:
    container_name: snakechain_buffer
    image: redis
