version: '3.7'

services:
  node:
    container_name: snakechain_node
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./snakechain:/app
      - ./docker/entrypoint.sh:/entrypoint.sh
    command: /./entrypoint.sh
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - STORAGE_HOST=db
    depends_on:
      - db
      - cache

  db:
    container_name: snakechain_db
    image: couchbase

  cache:
    container_name: snakechain_cache
    image: redis
