version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./snakechain/node:/app
      - ./docker/node/entrypoint.sh:/entrypoint.sh
    command: /./entrypoint.sh
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis

  rest:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    volumes:
      - ./snakechain/rest:/app
      - ./docker/rest/entrypoint.sh:/entrypoint.sh
    command: /./entrypoint.sh
    ports:
      - "8000:8000"
